### ISSUE TITLE
Optimization in checking that reads are done

### ISSUE THREAD

**Issue by boxley-tw-em** [binkley/kotlin-application-transactions#10]
In `WorkerPool` this code should use early return of `false` rather than accumulate a check:

```kotlin
fun areAllDone(): Boolean {
    var allDone = true
    for (task in runQueue) {
        allDone = allDone and task.isDone
    }
    return allDone
}
```

Early return here is both more performant, and easier to read and understand.

Also, review `awaitCompletion`, and also consider early return there.

**Comment by binkley** [comment]
Bonus: this also raises coverage.
